[technote]
id = "ITTN-081"
series_id = "ITTN"
canonical_url = "https://ittn-081.lsst.io"
github_url = "https://github.com/lsst-it/ittn-081"
github_default_branch = "main"
date_created = 2024-11-06T19:52:22Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Cristian"
name.family = "Silva"
internal_id = "silvac"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
